### ISSUE TITLE
红米打开设置闪退

### ISSUE THREAD

**Issue by zhouzhuo810** [getActivity/XXPermissions#161]
#### 问题描述

* 框架版本【必填】：16.0

* 问题描述【必填】：红米权限被拒后打开设置闪退
 XXPermissions.startPermissionActivity(BaseActivity.this, permissions);

* 复现步骤【必填】：XXX（注意：目前不受理没有复现步骤的 Bug 单）
 XXPermissions.startPermissionActivity(BaseActivity.this, permissions);

* 是否必现【必填】：填是/否，搞不清，用户手机报上来的

* 出现问题的手机信息【必填】：小米，红米
Device Manufacturer: Xiaomi
Device BRAND       : Redmi
Device DEVICE       : cannon
Device Model       : M2007J22C
Device Product       : cannon
Android Version    : 12
Android SDK        : 31
App VersionName    : 3.7.5
App VersionCode    : 222

* 出现问题的安卓版本【必填】：12

* 问题信息的来源渠道【必填】：自定义的CrashUtils

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：部分

* 框架最新的版本是否存在这个问题【必答】：不清楚

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：没设备，无法测试

* 使用原生的权限 API 是否会出现该问题【必答】：没设备，无法测试

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.MANAGE_APPLICATIONS_SETTINGS }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2087)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1886)
	at android.app.Activity.startActivityForResult(Activity.java:6202)
	at android.app.Activity.startActivityFromFragment(Activity.java:6180)
	at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:9070)
	at android.app.Fragment.startActivityForResult(Fragment.java:1121)
	at android.app.Fragment.startActivityForResult(Fragment.java:1110)
	at com.hjq.permissions.PermissionFragment.requestSpecialPermission(PermissionFragment.java:11)
	at com.hjq.permissions.PermissionFragment.onResume(PermissionFragment.java:6)
	at android.app.Fragment.performResume(Fragment.java:2551)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2220)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8273)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
[XXPermissions-16.3.aar.zip](https://github.com/getActivity/XXPermissions/files/9776582/XXPermissions-16.3.aar.zip)

**Comment by getActivity** [comment]
小伙子，介于你无法复现这个问题，我对这个问题尝试进行了修复，你可以下载上面的 aar 包进行发版测试，如果后续还有问题请在此 issue 下反馈给我，我会持续跟进。

**Comment by zhouzhuo810** [comment]
> 小伙子，介于你无法复现这个问题，我对这个问题尝试进行了修复，你可以下载上面的 aar 包进行发版测试，如果后续还有问题请在此 issue 下反馈给我，我会持续跟进。

好，我下个版本用这个aar

**Comment by getActivity** [comment]
还有小伙子，是否能提供一下这个 Bug 的崩溃次数、影响用户数、Android 机型、Android 版本分布信息？以便我做更好的判断。

**Comment by getActivity** [comment]
你这边如果用的是 Bugly 的话，上面说的这些信息你可以通过点击这里获得，你也可以直接截这个图发给我

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/28616817/195597407-1d982b08-626c-483e-9596-de69a87bdba3.png">

**Comment by zhouzhuo810** [comment]
> 还有小伙子，是否能提供一下这个 Bug 的崩溃次数、影响用户数、Android 机型、Android 版本分布信息？以便我做更好的判断。

目前只有一个手机上报，我之前用的umeng，umeng收费后最近改成自定义CrashUtils了，所以收集的还不算全面，bugly和umeng都后台收集用户隐私信息，所以索性现在都没接入了。

**Comment by getActivity** [comment]
@zhouzhuo810 小伙子，只有一个用户受影响吗？还是同个机型但是有多个用户会出现？另外这个 Bug 的总崩溃次数是多少？

**Comment by zhouzhuo810** [comment]
> @zhouzhuo810 小伙子，只有一个用户受影响吗？还是同个机型但是有多个用户会出现？另外这个 Bug 的总崩溃次数是多少？

目前是1个用户，崩溃了2次，影响不是很大，估计是特殊情况吧，也许是系统自己的问题，当然框架上能规避闪退是最好了，我查了下是红米Note9出现的。

**Comment by getActivity** [comment]
@zhouzhuo810 小伙子，我觉得你没有必要为了一个用户而大惊小怪，这个用户也有可能是 miui 工程师在调试某个功能导致的，关于捕获崩溃这件事上，我觉得捕获异常始终是下下策，一旦异常被捕获，也将意味着很多问题会被掩盖掉，万一是厂商的 Bug，厂商是收不到这个异常上报的，万一我的代码写得有问题，那么我是不知道的，作为框架作者来讲，应该写出更严谨的代码，而不是一味使用 try catch 解决问题，加个 try catch 其实很简单，但是我为什么不加？加了崩溃率确实好看了一点，但是又有什么用呢？这难道不是寻求自我安慰么？那么这个时候关键是需要你能复现这个问题，并和我一起排查和研究这个问题，最终得出结论及方案，经过深思熟虑之后我才会改。

**Comment by zhouzhuo810** [comment]
> @zhouzhuo810 小伙子，我觉得你没有必要为了一个用户而大惊小怪，这个用户也有可能是 miui 工程师在调试某个功能导致的，关于捕获崩溃这件事上，我觉得捕获异常始终是下下策，一旦异常被捕获，也将意味着很多问题会被掩盖掉，万一是厂商的 Bug，厂商是收不到这个异常上报的，万一我的代码写得有问题，那么我是不知道的，作为框架作者来讲，应该写出更严谨的代码，而不是一味使用 try catch 解决问题，加个 try catch 其实很简单，但是我为什么不加？加了崩溃率确实好看了一点，但是又有什么用呢？这难道不是寻求自我安慰么？那么这个时候关键是需要你能复现这个问题，并和我一起排查和研究这个问题，最终得出结论及方案，经过深思熟虑之后我才会改。

那好吧，估计是个人现象，以后遇到了再说吧，我先关了哈。
