### ISSUE TITLE
[Bug]：适配Android13后，在Android9.0及以下机型，存储权限问题

### ISSUE THREAD

**Issue by liyongTest** [getActivity/XXPermissions#210]
### 框架版本【必填】

18.2

### 问题描述【必填】

Android 9.0及以下版本，框架存储权限没有同时申请”android.permission.WRITE_EXTERNAL_STORAGE“

### 复现步骤【必填】

新框架在Android9.0测试

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

xiaomi

### 出现问题的安卓版本【必填】

9.0

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=13406, uid=10462 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
                                                                                                    	at android.os.Parcel.createException(Parcel.java:1953)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:1921)
                                                                                                    	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                                                    	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                                                    	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
                                                                                                    	at android.content.ContentResolver.insert(ContentResolver.java:1603)
```

**Comment by swanfly** [comment]
我也遇到这个问题了，compileSdkVersion和targetSdkVersion设为33后，Android版本为13的手机，存储权限就会有问题。

**Comment by liyongTest** [comment]
> 我也遇到这个问题了，compileSdkVersion和targetSdkVersion设为33后，Android版本为13的手机，存储权限就会有问题。

我看了源码，针对Android9及以下，没有申请"android.permission.WRITE_EXTERNAL_STORAGE"

**Comment by liyongTest** [comment]
临时解决方案：在申请存储相关权限时，Android9及以下系统手动添加"android.permission.WRITE_EXTERNAL_STORAGE"权限

**Comment by getActivity** [comment]
小伙子，你申请的是什么权限？

**Comment by liyongTest** [comment]
> 小伙子，你申请的是什么权限？

    const val READ_MEDIA_IMAGES = "android.permission.READ_MEDIA_IMAGES"
    const val READ_MEDIA_VIDEO = "android.permission.READ_MEDIA_VIDEO"
    const val READ_MEDIA_AUDIO = "android.permission.READ_MEDIA_AUDIO"

**Comment by getActivity** [comment]
小伙子，你这个问题之前已有人提过了，并且我已经处理过了，请不要重复提问。

**Comment by getActivity** [comment]
小伙子，你这个问题之前已有人提过了，并且我已经处理过了，请不要重复提问。

**Comment by liyongTest** [comment]
> 小伙子，你这个问题之前已有人提过了，并且我已经处理过了，请不要重复提问。

大佬，Android9.0以下，有写文件的操作会提示 无android.permission.WRITE_EXTERNAL_STORAGE权限，我看框架源码中确实是没有申请这个权限
