### ISSUE TITLE
[Bug]：权限申请直接闪退

### ISSUE THREAD

**Issue by zabio** [getActivity/XXPermissions#217]
### 框架版本【必填】

18.2

### 问题描述【必填】

targetSdkVersion >= 33 使用权限申请

### 复现步骤【必填】

调用
 XXPermissions.with(this).permission(Permission.Group.STORAGE)

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

IQOO10 Pro

### 出现问题的安卓版本【必填】

13

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

否

### 提供报错堆栈

```text
Caused by: java.lang.IllegalArgumentException: When targetSdkVersion >= 33 should use android.permission.READ_MEDIA_IMAGES, android.permission.READ_MEDIA_VIDEO, android.permission.READ_MEDIA_AUDIO instead of android.permission.READ_EXTERNAL_STORAGE
                                                 	at com.hjq.permissions.PermissionChecker.checkStoragePermission(PermissionChecker.java:172)
                                                 	at com.hjq.permissions.XXPermissions.request(XXPermissions.java:174)
```

**Comment by getActivity** [comment]
小伙子，你翻译一下这个报错就知道是什么意思了

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。

**Comment by flysands** [comment]
我也遇到了。debug版本有这个问题，release版本正常。

**Comment by Huping95** [comment]
+1，debug崩溃，release正常，求解答

**Comment by getActivity** [comment]
@flysands @Huping95 小伙子，你们看文档了吗？

**Comment by Huping95** [comment]
@getActivity 我是傻逼
