### ISSUE TITLE
[Bug]：权限拦截器在部分华为手机上出现闪退，提示没有实现的抽象方法

### ISSUE THREAD

**Issue by lucky013** [getActivity/XXPermissions#266]
### 框架版本【必填】

18.5

### 问题描述【必填】

申请相机权限成功后闪退，其他权限应该也会

### 复现步骤【必填】

使用框架申请权限->授予权限->闪退

### 是否必现【必填】

否

### 项目 targetSdkVersion【必填】

30

### 出现问题的手机信息【必填】

P50 HarmonyOs 4.0.0，mate50 pro

### 出现问题的安卓版本【必填】

Android 12

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

部分，某为会

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
java.lang.AbstractMethodError: abstract method "void com.hjq.permissions.IPermissionInterceptor.finishPermissionRequest(android.app.Activity, java.util.List, boolean, com.hjq.permissions.OnPermissionCallback)"
                                                                                                    	at com.hjq.permissions.XXPermissions.request(XXPermissions.java:210)
                                                                                                    	at com.feisukj.heart_rate.ui.activity.HomeActivity2.startMeasurement(HomeActivity2.kt:315)
                                                                                                    	at com.feisukj.heart_rate.ui.activity.HomeActivity2.initListener$lambda$8(HomeActivity2.kt:220)
                                                                                                    	at com.feisukj.heart_rate.ui.activity.HomeActivity2.$r8$lambda$-jQ-RXKJDhpz-szCfTnjan7SP3s(Unknown Source:0)
                                                                                                    	at com.feisukj.heart_rate.ui.activity.HomeActivity2$$ExternalSyntheticLambda16.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:7682)
                                                                                                    	at android.view.View.performClickInternal(View.java:7651)
                                                                                                    	at android.view.View.access$3700(View.java:886)
                                                                                                    	at android.view.View$PerformClick.run(View.java:30173)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:966)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:293)
                                                                                                    	at android.app.ActivityThread.loopProcess(ActivityThread.java:9934)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9923)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)
```

**Comment by getActivity** [comment]
<img width="859" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/43ecd871-1b61-4b63-b420-a55b9e24a926">

**Comment by getActivity** [comment]
小伙子，你的项目有加入这个 `Java JDK 8` 配置？

**Comment by lucky013** [comment]
配置了还是会闪退，使用Android studio安装不会闪退，使用安装包安装会闪退

Android轮子哥 ***@***.***> 于2024年1月26日周五 17:04写道：

**Comment by getActivity** [comment]
<img width="362" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/5a45a651-07c1-43da-b580-2ec1a74792e8">

@lucky013 小伙子，请提供一个可供复现的 Demo 给我。

**Comment by lucky013** [comment]
之前用的aar依赖有闪退，现在换成远程依赖，又不会有闪退了。

然后我用aar建了个demo又不会闪退。

有可能是我原项目依赖太多了吧。

麻烦你了，现在没问题了

Android轮子哥 ***@***.***> 于2024年2月1日周四 12:15写道：
