### ISSUE TITLE
小米5sPLUS和小米mimix申请权限崩溃，请作者看一下。

### ISSUE THREAD

**Issue by wuconghui** [getActivity/XXPermissions#27]
java.lang.IllegalStateException: Fragment PermissionFragment{9a606ea} not attached to Activity
at android.app.Fragment.requestPermissions(Fragment.java:1328)
at com.hjq.permissions.PermissionFragment.requestPermission(PermissionFragment.java:93)
at com.hjq.permissions.PermissionFragment.run(PermissionFragment.java:187)

**Comment by getActivity** [comment]
怎么复现？

**Comment by getActivity** [comment]
长时间没有答复，关闭此issues
