### ISSUE TITLE
[Bug]: /system/build.prop: open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by cr4sh-me** [getActivity/XXPermissions#274]
### Framework Version [Required]

18.62

### Issue Description [Required]

After granting file permissions on android 14 warning occurs

### Steps to Reproduce [Required]
```
XXPermissions.with(this)
                .permission(Permission.MANAGE_EXTERNAL_STORAGE)
                .request(object : OnPermissionCallback {
                    override fun onGranted(permissions: MutableList<String>, allGranted: Boolean) {
                        isBatteryOptimizationRemoved = allGranted
                        checkPermissionAndStartMain()
                    }

                    override fun onDenied(permissions: MutableList<String>, doNotAskAgain: Boolean) {
                        if (doNotAskAgain) {
                            lifecycleScope.launch {
                               // code ...
                            }
                        } else {
                            lifecycleScope.launch {
                                // code ....
                            }
                        }
                    }
                })
```
### Is the Issue Reproducible? [Required]

Not Selected

### Project targetSdkVersion [Required]

34

### Device Information [Required]

Nothing Phone 1

### Android Version [Required]

14

### Issue Source Channel [Required]

Encountered by myself

### Is it specific to certain device models? [Required]

No

### Does the latest version of the framework have this issue? [Required]

Yes

### Is the issue mentioned in the framework documentation? [Required]

No

### Did you consult the framework documentation but couldn't find a solution? [Required]

Yes

### Has a similar issue been reported in the issue list? [Required]

No

### Have you searched the issue list but couldn't find a solution? [Required]

Yes

### Can the issue be reproduced with a demo project? [Required]

Yes

### Provide Error Stack Trace

```text
2024-03-29 14:35:32.757 17144-17144 System.err              com.hjq.permissions.demo             W  java.io.FileNotFoundException: /system/build.prop: open failed: EACCES (Permission denied)
2024-03-29 14:35:32.757 17144-17144 System.err              com.hjq.permissions.demo             W  	at libcore.io.IoBridge.open(IoBridge.java:574)
2024-03-29 14:35:32.757 17144-17144 System.err              com.hjq.permissions.demo             W  	at java.io.FileInputStream.<init>(FileInputStream.java:160)
2024-03-29 14:35:32.757 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.getSystemPropertyByStream(PhoneRomUtils.java:300)
2024-03-29 14:35:32.758 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.getSystemProperty(PhoneRomUtils.java:263)
2024-03-29 14:35:32.758 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.getPropertyName(PhoneRomUtils.java:253)
2024-03-29 14:35:32.758 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.isEmui(PhoneRomUtils.java:62)
2024-03-29 14:35:32.758 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PermissionUtils.postActivityResult(PermissionUtils.java:128)
2024-03-29 14:35:32.758 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PermissionFragment.onActivityResult(PermissionFragment.java:449)
2024-03-29 14:35:32.758 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.Activity.dispatchActivityResult(Activity.java:8995)
2024-03-29 14:35:32.758 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.deliverResults(ActivityThread.java:5562)
2024-03-29 14:35:32.758 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5608)
2024-03-29 14:35:32.758 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
2024-03-29 14:35:32.758 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
2024-03-29 14:35:32.758 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
2024-03-29 14:35:32.758 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
2024-03-29 14:35:32.759 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469)
2024-03-29 14:35:32.759 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2024-03-29 14:35:32.759 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.os.Looper.loopOnce(Looper.java:205)
2024-03-29 14:35:32.759 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.os.Looper.loop(Looper.java:294)
2024-03-29 14:35:32.759 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.main(ActivityThread.java:8294)
2024-03-29 14:35:32.759 17144-17144 System.err              com.hjq.permissions.demo             W  	at java.lang.reflect.Method.invoke(Native Method)
2024-03-29 14:35:32.759 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
2024-03-29 14:35:32.759 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
2024-03-29 14:35:32.759 17144-17144 System.err              com.hjq.permissions.demo             W  Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
2024-03-29 14:35:32.759 17144-17144 System.err              com.hjq.permissions.demo             W  	at libcore.io.Linux.open(Native Method)
2024-03-29 14:35:32.759 17144-17144 System.err              com.hjq.permissions.demo             W  	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
2024-03-29 14:35:32.760 17144-17144 System.err              com.hjq.permissions.demo             W  	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
2024-03-29 14:35:32.760 17144-17144 System.err              com.hjq.permissions.demo             W  	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
2024-03-29 14:35:32.760 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8180)
2024-03-29 14:35:32.760 17144-17144 System.err              com.hjq.permissions.demo             W  	at libcore.io.IoBridge.open(IoBridge.java:560)
2024-03-29 14:35:32.760 17144-17144 System.err              com.hjq.permissions.demo             W  	... 22 more
2024-03-29 14:35:32.760 17144-17144 System.err              com.hjq.permissions.demo             W  java.lang.ClassNotFoundException: com.huawei.system.BuildEx
2024-03-29 14:35:32.760 17144-17144 System.err              com.hjq.permissions.demo             W  	at java.lang.Class.classForName(Native Method)
2024-03-29 14:35:32.760 17144-17144 System.err              com.hjq.permissions.demo             W  	at java.lang.Class.forName(Class.java:536)
2024-03-29 14:35:32.760 17144-17144 System.err              com.hjq.permissions.demo             W  	at java.lang.Class.forName(Class.java:467)
2024-03-29 14:35:32.760 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.isHarmonyOs(PhoneRomUtils.java:124)
2024-03-29 14:35:32.761 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PermissionUtils.postActivityResult(PermissionUtils.java:128)
2024-03-29 14:35:32.761 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PermissionFragment.onActivityResult(PermissionFragment.java:449)
2024-03-29 14:35:32.761 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.Activity.dispatchActivityResult(Activity.java:8995)
2024-03-29 14:35:32.761 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.deliverResults(ActivityThread.java:5562)
2024-03-29 14:35:32.761 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5608)
2024-03-29 14:35:32.761 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
2024-03-29 14:35:32.761 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
2024-03-29 14:35:32.761 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
2024-03-29 14:35:32.761 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
2024-03-29 14:35:32.761 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469)
2024-03-29 14:35:32.761 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2024-03-29 14:35:32.761 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.os.Looper.loopOnce(Looper.java:205)
2024-03-29 14:35:32.761 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.os.Looper.loop(Looper.java:294)
2024-03-29 14:35:32.761 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.main(ActivityThread.java:8294)
2024-03-29 14:35:32.762 17144-17144 System.err              com.hjq.permissions.demo             W  	at java.lang.reflect.Method.invoke(Native Method)
2024-03-29 14:35:32.762 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
2024-03-29 14:35:32.762 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
2024-03-29 14:35:32.762 17144-17144 System.err              com.hjq.permissions.demo             W  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.huawei.system.BuildEx" on path: DexPathList[[zip file "/data/app/~~zTZCJCdGsx50kZCWayF89w==/com.hjq.permissions.demo-B_rb2LNkY4p45Gifcm2GbA==/base.apk"],nativeLibraryDirectories=[/data/app/~~zTZCJCdGsx50kZCWayF89w==/com.hjq.permissions.demo-B_rb2LNkY4p45Gifcm2GbA==/lib/arm64, /system/lib64, /system_ext/lib64]]
2024-03-29 14:35:32.762 17144-17144 System.err              com.hjq.permissions.demo             W  	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
2024-03-29 14:35:32.762 17144-17144 System.err              com.hjq.permissions.demo             W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2024-03-29 14:35:32.762 17144-17144 System.err              com.hjq.permissions.demo             W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2024-03-29 14:35:32.762 17144-17144 System.err              com.hjq.permissions.demo             W  	... 21 more
2024-03-29 14:35:32.767 17144-17144 System.err              com.hjq.permissions.demo             W  java.io.FileNotFoundException: /system/build.prop: open failed: EACCES (Permission denied)
2024-03-29 14:35:32.767 17144-17144 System.err              com.hjq.permissions.demo             W  	at libcore.io.IoBridge.open(IoBridge.java:574)
2024-03-29 14:35:32.767 17144-17144 System.err              com.hjq.permissions.demo             W  	at java.io.FileInputStream.<init>(FileInputStream.java:160)
2024-03-29 14:35:32.767 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.getSystemPropertyByStream(PhoneRomUtils.java:300)
2024-03-29 14:35:32.767 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.getSystemProperty(PhoneRomUtils.java:263)
2024-03-29 14:35:32.768 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.getPropertyName(PhoneRomUtils.java:253)
2024-03-29 14:35:32.768 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.isMiui(PhoneRomUtils.java:69)
2024-03-29 14:35:32.768 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PermissionUtils.postActivityResult(PermissionUtils.java:135)
2024-03-29 14:35:32.768 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PermissionFragment.onActivityResult(PermissionFragment.java:449)
2024-03-29 14:35:32.768 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.Activity.dispatchActivityResult(Activity.java:8995)
2024-03-29 14:35:32.768 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.deliverResults(ActivityThread.java:5562)
2024-03-29 14:35:32.768 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5608)
2024-03-29 14:35:32.768 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
2024-03-29 14:35:32.768 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
2024-03-29 14:35:32.768 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
2024-03-29 14:35:32.768 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
2024-03-29 14:35:32.768 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469)
2024-03-29 14:35:32.769 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2024-03-29 14:35:32.769 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.os.Looper.loopOnce(Looper.java:205)
2024-03-29 14:35:32.769 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.os.Looper.loop(Looper.java:294)
2024-03-29 14:35:32.769 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.main(ActivityThread.java:8294)
2024-03-29 14:35:32.769 17144-17144 System.err              com.hjq.permissions.demo             W  	at java.lang.reflect.Method.invoke(Native Method)
2024-03-29 14:35:32.769 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
2024-03-29 14:35:32.769 17144-17144 System.err              com.hjq.permissions.demo             W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
2024-03-29 14:35:32.769 17144-17144 System.err              com.hjq.permissions.demo             W  Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
2024-03-29 14:35:32.769 17144-17144 System.err              com.hjq.permissions.demo             W  	at libcore.io.Linux.open(Native Method)
2024-03-29 14:35:32.769 17144-17144 System.err              com.hjq.permissions.demo             W  	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
2024-03-29 14:35:32.769 17144-17144 System.err              com.hjq.permissions.demo             W  	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
2024-03-29 14:35:32.769 17144-17144 System.err              com.hjq.permissions.demo             W  	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
2024-03-29 14:35:32.770 17144-17144 System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8180)
2024-03-29 14:35:32.770 17144-17144 System.err              com.hjq.permissions.demo             W  	at libcore.io.IoBridge.open(IoBridge.java:560)
2024-03-29 14:35:32.770 17144-17144 System.err              com.hjq.permissions.demo             W  	... 22 more
```

**Comment by getActivity** [comment]
Hello, this is just a warning log, it will not have any impact.
