### ISSUE TITLE
[Bug]：MANAGE_EXTERNAL_STORAGE没有回调，并且会出现重启的现象

### ISSUE THREAD

**Issue by liuyaxi** [getActivity/XXPermissions#289]
### 框架版本【必填】

implementation 'com.github.getActivity:XXPermissions:18.63'

### 问题描述【必填】

申请Permission.MANAGE_EXTERNAL_STORAGE权限不会有拒绝后的权限回调

### 复现步骤【必填】

申请MANAGE_EXTERNAL_STORAGE权限的时候，允许管理所有文件权限勾选上，然后再关闭。这个时候这几左上角的返回键返回！
onDenied此方法不会有回调。具体操作可以看演示视频

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

Vivo s16

### 出现问题的安卓版本【必填】

android13

### 问题信息的来源渠道【必填】

自己遇到的, 用户反馈

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
java.io.FileNotFoundException: /system/build.prop: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at com.hjq.permissions.PhoneRomUtils.getSystemPropertyByStream(PhoneRomUtils.java:300)
	at com.hjq.permissions.PhoneRomUtils.getSystemProperty(PhoneRomUtils.java:263)
	at com.hjq.permissions.PhoneRomUtils.getPropertyName(PhoneRomUtils.java:253)
	at com.hjq.permissions.PhoneRomUtils.isEmui(PhoneRomUtils.java:62)
	at com.hjq.permissions.PermissionUtils.postActivityResult(PermissionUtils.java:128)
	at com.hjq.permissions.PermissionFragment.onActivityResult(PermissionFragment.java:449)
	at android.app.Activity.dispatchActivityResult(Activity.java:9134)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5730)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5146)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5198)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
Compiler allocated 4190KB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2545)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at android.app.ActivityThread.main(ActivityThread.java:8531)

2024-05-11 10:05:16.159 20226-20226 System.err              com.hjq.permissions.demo             W  	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1059)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8402)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 23 more
java.lang.ClassNotFoundException: com.huawei.system.BuildEx
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.lang.Class.forName(Class.java:379)
	at com.hjq.permissions.PhoneRomUtils.isHarmonyOs(PhoneRomUtils.java:124)
	at com.hjq.permissions.PermissionUtils.postActivityResult(PermissionUtils.java:128)
	at com.hjq.permissions.PermissionFragment.onActivityResult(PermissionFragment.java:449)
	at android.app.Activity.dispatchActivityResult(Activity.java:9134)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5730)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5146)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5198)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2545)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at android.app.ActivityThread.main(ActivityThread.java:8531)

2024-05-11 10:05:16.160 20226-20226 System.err              com.hjq.permissions.demo             W  	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1059)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.huawei.system.BuildEx" on path: DexPathList[[dex file "/data/data/com.hjq.permissions.demo/code_cache/.overlay/base.apk/classes.dex", zip file "/data/app/~~aqy_X2T4OMCz2_cA1jxupQ==/com.hjq.permissions.demo-rCFDV9_KnwKfqdbiG4QE8Q==/base
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 22 more
java.io.FileNotFoundException: /system/build.prop: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at com.hjq.permissions.PhoneRomUtils.getSystemPropertyByStream(PhoneRomUtils.java:300)
	at com.hjq.permissions.PhoneRomUtils.getSystemProperty(PhoneRomUtils.java:263)
	at com.hjq.permissions.PhoneRomUtils.getPropertyName(PhoneRomUtils.java:253)
	at com.hjq.permissions.PhoneRomUtils.isMiui(PhoneRomUtils.java:69)
	at com.hjq.permissions.PermissionUtils.postActivityResult(PermissionUtils.java:135)
	at com.hjq.permissions.PermissionFragment.onActivityResult(PermissionFragment.java:449)
	at android.app.Activity.dispatchActivityResult(Activity.java:9134)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5730)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5146)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5198)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2545)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at android.app.ActivityThread.main(ActivityThread.java:8531)

2024-05-11 10:05:16.165 20226-20226 System.err              com.hjq.permissions.demo             W  	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1059)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8402)
	at libcore.io.IoBridge.open(IoBridge.java:560)
```

### 提供截图或视频

https://github.com/getActivity/XXPermissions/assets/17871784/785b4780-8c67-41ae-a2d7-d5503b973495

**Comment by getActivity** [comment]
https://github.com/getActivity/XXPermissions/issues/227

**Comment by getActivity** [comment]
小伙子，你确定这个问题没有人提过？
