### ISSUE TITLE
[Bug]：java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by shiner0** [getActivity/XXPermissions#297]
### 框架版本【必填】

18.63

### 问题描述【必填】

 public static final String[] permissionGroup = new String[]{
            "android.permission.CAMERA",
            "android.permission.READ_SMS",
            "android.permission.READ_CALENDAR",
            "android.permission.READ_PHONE_STATE",
            "android.permission.ACCESS_COARSE_LOCATION",
            "android.permission.READ_CALL_LOG"
    };
授权过程中报错

### 复现步骤【必填】

同上

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

小米MAX2 

### 出现问题的安卓版本【必填】

安卓10

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

小米MAX2  安卓10

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
java.lang.NoSuchMethodError: No virtual method query(Landroid/net/Uri;[Ljava/lang/String;Landroid/os/Bundle;Landroid/os/CancellationSignal;)Landroid/database/Cursor; in class Landroid/content/ContentResolver; or its super classes (declaration of 'android.content.ContentResolver' appears in /system/framework/framework.jar)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at e2.a.v(SourceFile:2)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at n2.f1.onGranted(SourceFile:15)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at com.hjq.permissions.b.c(SourceFile:4)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at com.hjq.permissions.XXPermissions$1.grantedPermissionRequest(SourceFile:1)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at com.hjq.permissions.XXPermissions.request(SourceFile)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at com.app.scci.kuai.page.WelActivity.onActivityResult(SourceFile:23)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at android.app.Activity.dispatchActivityResult(Activity.java:7118)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4218)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4265)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1614)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at android.os.Looper.loop(Looper.java:163)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at android.app.ActivityThread.main(ActivityThread.java:6388)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at java.lang.reflect.Method.invoke(Native Method)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:930)
06-17 10:24:48.644 E/AndroidRuntime(27552): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)
```

**Comment by getActivity** [comment]
<img width="845" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/ab85811d-cfdf-4158-8c6f-0f964dc3c8b0">

小伙子，这个问题不是你自己的代码导致？

**Comment by shiner0** [comment]
找到问题了谢谢！
