### ISSUE TITLE
[Bug]：所有文件权限开启随后关闭再返回白屏

### ISSUE THREAD

**Issue by xujiaji** [getActivity/XXPermissions#298]
### 框架版本【必填】

18.63

### 问题描述【必填】

跳转到系统所有文件授权界面后开关权限返回白屏

### 复现步骤【必填】

跳转到系统所有文件授权界面后，开启权限开关，然后关闭权限开关，返回界面白屏，demo可以复现。

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

OPPO A11

### 出现问题的安卓版本【必填】

11

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

所有机型

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
2024-06-20 17:37:13.930  6685-6685  OplusCusto...ionManager com.hjq.permissions.demo             E  sInstance is null, start a new sInstance
2024-06-20 17:37:14.061  6685-6685  System.err              com.hjq.permissions.demo             W  java.io.FileNotFoundException: /system/build.prop: open failed: EACCES (Permission denied)
2024-06-20 17:37:14.061  6685-6685  System.err              com.hjq.permissions.demo             W  	at libcore.io.IoBridge.open(IoBridge.java:492)
2024-06-20 17:37:14.062  6685-6685  System.err              com.hjq.permissions.demo             W  	at java.io.FileInputStream.<init>(FileInputStream.java:160)
2024-06-20 17:37:14.062  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.getSystemPropertyByStream(PhoneRomUtils.java:300)
2024-06-20 17:37:14.062  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.getSystemProperty(PhoneRomUtils.java:263)
2024-06-20 17:37:14.062  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.getPropertyName(PhoneRomUtils.java:253)
2024-06-20 17:37:14.062  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.isEmui(PhoneRomUtils.java:62)
2024-06-20 17:37:14.062  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PermissionUtils.postActivityResult(PermissionUtils.java:128)
2024-06-20 17:37:14.062  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PermissionFragment.onActivityResult(PermissionFragment.java:449)
2024-06-20 17:37:14.062  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.Activity.dispatchActivityResult(Activity.java:8491)
2024-06-20 17:37:14.062  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.deliverResults(ActivityThread.java:5369)
2024-06-20 17:37:14.062  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4758)
2024-06-20 17:37:14.062  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4813)
2024-06-20 17:37:14.062  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
2024-06-20 17:37:14.062  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
2024-06-20 17:37:14.063  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
2024-06-20 17:37:14.063  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
2024-06-20 17:37:14.063  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2024-06-20 17:37:14.063  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.os.Looper.loop(Looper.java:263)
2024-06-20 17:37:14.063  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.main(ActivityThread.java:8292)
2024-06-20 17:37:14.063  6685-6685  System.err              com.hjq.permissions.demo             W  	at java.lang.reflect.Method.invoke(Native Method)
2024-06-20 17:37:14.063  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
2024-06-20 17:37:14.063  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
2024-06-20 17:37:14.063  6685-6685  System.err              com.hjq.permissions.demo             W  Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
2024-06-20 17:37:14.063  6685-6685  System.err              com.hjq.permissions.demo             W  	at libcore.io.Linux.open(Native Method)
2024-06-20 17:37:14.064  6685-6685  System.err              com.hjq.permissions.demo             W  	at libcore.io.ForwardingOs.open(ForwardingOs.java:170)
2024-06-20 17:37:14.064  6685-6685  System.err              com.hjq.permissions.demo             W  	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
2024-06-20 17:37:14.064  6685-6685  System.err              com.hjq.permissions.demo             W  	at libcore.io.ForwardingOs.open(ForwardingOs.java:170)
2024-06-20 17:37:14.064  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8165)
2024-06-20 17:37:14.064  6685-6685  System.err              com.hjq.permissions.demo             W  	at libcore.io.IoBridge.open(IoBridge.java:478)
2024-06-20 17:37:14.064  6685-6685  System.err              com.hjq.permissions.demo             W  	... 21 more
2024-06-20 17:37:14.064  6685-6685  System.err              com.hjq.permissions.demo             W  java.lang.ClassNotFoundException: com.huawei.system.BuildEx
2024-06-20 17:37:14.065  6685-6685  System.err              com.hjq.permissions.demo             W  	at java.lang.Class.classForName(Native Method)
2024-06-20 17:37:14.065  6685-6685  System.err              com.hjq.permissions.demo             W  	at java.lang.Class.forName(Class.java:454)
2024-06-20 17:37:14.065  6685-6685  System.err              com.hjq.permissions.demo             W  	at java.lang.Class.forName(Class.java:379)
2024-06-20 17:37:14.065  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.isHarmonyOs(PhoneRomUtils.java:124)
2024-06-20 17:37:14.065  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PermissionUtils.postActivityResult(PermissionUtils.java:128)
2024-06-20 17:37:14.065  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PermissionFragment.onActivityResult(PermissionFragment.java:449)
2024-06-20 17:37:14.065  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.Activity.dispatchActivityResult(Activity.java:8491)
2024-06-20 17:37:14.065  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.deliverResults(ActivityThread.java:5369)
2024-06-20 17:37:14.065  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4758)
2024-06-20 17:37:14.065  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4813)
2024-06-20 17:37:14.065  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
2024-06-20 17:37:14.065  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
2024-06-20 17:37:14.066  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
2024-06-20 17:37:14.066  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
2024-06-20 17:37:14.066  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2024-06-20 17:37:14.066  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.os.Looper.loop(Looper.java:263)
2024-06-20 17:37:14.066  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.main(ActivityThread.java:8292)
2024-06-20 17:37:14.066  6685-6685  System.err              com.hjq.permissions.demo             W  	at java.lang.reflect.Method.invoke(Native Method)
2024-06-20 17:37:14.066  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
2024-06-20 17:37:14.066  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
2024-06-20 17:37:14.066  6685-6685  System.err              com.hjq.permissions.demo             W  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.huawei.system.BuildEx" on path: DexPathList[[zip file "/data/app/~~6Qm3IqJKdjfhUK8kac1UJA==/com.hjq.permissions.demo-vjlcuqhjXeVL8ExNRNCsWg==/base.apk"],nativeLibraryDirectories=[/data/app/~~6Qm3IqJKdjfhUK8kac1UJA==/com.hjq.permissions.demo-vjlcuqhjXeVL8ExNRNCsWg==/lib/arm64, /system/lib64, /system/system_ext/lib64, /vendor/lib64, /odm/lib64]]
2024-06-20 17:37:14.066  6685-6685  System.err              com.hjq.permissions.demo             W  	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
2024-06-20 17:37:14.066  6685-6685  System.err              com.hjq.permissions.demo             W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2024-06-20 17:37:14.067  6685-6685  System.err              com.hjq.permissions.demo             W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2024-06-20 17:37:14.067  6685-6685  System.err              com.hjq.permissions.demo             W  	... 20 more
2024-06-20 17:37:14.074  6685-6685  System.err              com.hjq.permissions.demo             W  java.io.FileNotFoundException: /system/build.prop: open failed: EACCES (Permission denied)
2024-06-20 17:37:14.074  6685-6685  System.err              com.hjq.permissions.demo             W  	at libcore.io.IoBridge.open(IoBridge.java:492)
2024-06-20 17:37:14.074  6685-6685  System.err              com.hjq.permissions.demo             W  	at java.io.FileInputStream.<init>(FileInputStream.java:160)
2024-06-20 17:37:14.074  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.getSystemPropertyByStream(PhoneRomUtils.java:300)
2024-06-20 17:37:14.075  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.getSystemProperty(PhoneRomUtils.java:263)
2024-06-20 17:37:14.075  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.getPropertyName(PhoneRomUtils.java:253)
2024-06-20 17:37:14.075  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PhoneRomUtils.isMiui(PhoneRomUtils.java:69)
2024-06-20 17:37:14.075  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PermissionUtils.postActivityResult(PermissionUtils.java:135)
2024-06-20 17:37:14.075  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.hjq.permissions.PermissionFragment.onActivityResult(PermissionFragment.java:449)
2024-06-20 17:37:14.075  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.Activity.dispatchActivityResult(Activity.java:8491)
2024-06-20 17:37:14.075  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.deliverResults(ActivityThread.java:5369)
2024-06-20 17:37:14.075  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4758)
2024-06-20 17:37:14.075  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4813)
2024-06-20 17:37:14.075  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
2024-06-20 17:37:14.075  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
2024-06-20 17:37:14.075  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
2024-06-20 17:37:14.075  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
2024-06-20 17:37:14.075  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2024-06-20 17:37:14.075  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.os.Looper.loop(Looper.java:263)
2024-06-20 17:37:14.076  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread.main(ActivityThread.java:8292)
2024-06-20 17:37:14.076  6685-6685  System.err              com.hjq.permissions.demo             W  	at java.lang.reflect.Method.invoke(Native Method)
2024-06-20 17:37:14.076  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
2024-06-20 17:37:14.076  6685-6685  System.err              com.hjq.permissions.demo             W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
2024-06-20 17:37:14.076  6685-6685  System.err              com.hjq.permissions.demo             W  Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
2024-06-20 17:37:14.076  6685-6685  System.err              com.hjq.permissions.demo             W  	at libcore.io.Linux.open(Native Method)
2024-06-20 17:37:14.076  6685-6685  System.err              com.hjq.permissions.demo             W  	at libcore.io.ForwardingOs.open(ForwardingOs.java:170)
2024-06-20 17:37:14.076  6685-6685  System.err              com.hjq.permissions.demo             W  	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
2024-06-20 17:37:14.076  6685-6685  System.err              com.hjq.permissions.demo             W  	at libcore.io.ForwardingOs.open(ForwardingOs.java:170)
2024-06-20 17:37:14.076  6685-6685  System.err              com.hjq.permissions.demo             W  	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8165)
2024-06-20 17:37:14.076  6685-6685  System.err              com.hjq.permissions.demo             W  	at libcore.io.IoBridge.open(IoBridge.java:478)
2024-06-20 17:37:14.076  6685-6685  System.err              com.hjq.permissions.demo             W  	... 21 more
2024-06-20 17:37:14.078  6685-6685  LeakCanary              com.hjq.permissions.demo             D  Watching instance of com.hjq.permissions.PermissionFragment (com.hjq.permissions.PermissionFragment received Fragment#onDestroy() callback) with key 865248cd-f7c4-4d3d-98b5-075acfefdde8
2024-06-20 17:37:14.084  6685-6685  OplusInputMethodUtil    com.hjq.permissions.demo             D  init DEBUG to false, update DEBUG_IME to false
2024-06-20 17:37:14.092  6685-6685  ColorViewRootUtil       com.hjq.permissions.demo             D  initSwipState, isDisplayCompatApp false
2024-06-20 17:37:14.092  6685-6685  ColorViewRootUtil       com.hjq.permissions.demo             D  mScreenHeight 1600, mScreenWidth 720
2024-06-20 17:37:14.096  6685-6685  ermissions.dem          com.hjq.permissions.demo             W  Accessing hidden field Lcom/android/internal/policy/DecorView;->mWindow:Lcom/android/internal/policy/PhoneWindow; (greylist, reflection, allowed)
2024-06-20 17:37:14.098  6685-6685  WindowManager           com.hjq.permissions.demo             D  Add to mViews: DecorView@93ec3b7[MainActivity],pkg= com.hjq.permissions.demo
2024-06-20 17:37:14.190  6685-6685  OplusZoomW...ViewHelper com.hjq.permissions.demo             V  setLastReportedMergedConfiguration mZoomDisplayHeight: 1600 getDecorView.DecorView@93ec3b7[MainActivity]
2024-06-20 17:37:14.193  6685-6711  libEGL                  com.hjq.permissions.demo             E  Invalid file path for libcolorx-loader.so
2024-06-20 17:37:14.193  6685-6711  AdrenoGLES-0            com.hjq.permissions.demo             I  QUALCOMM build                   : 319c6d8, Ic907de5ed0
                                                                                                    Build Date                       : 09/21/20
                                                                                                    OpenGL ES Shader Compiler Version: EV031.32.02.01
                                                                                                    Local Branch                     : 
                                                                                                    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.9.11.R1.10.00.00.679.015
                                                                                                    Remote Branch                    : NONE
                                                                                                    Reconstruct Branch               : NOTHING
2024-06-20 17:37:14.194  6685-6711  AdrenoGLES-0            com.hjq.permissions.demo             I  Build Config                     : S P 10.0.5 AArch64
2024-06-20 17:37:14.194  6685-6711  AdrenoGLES-0            com.hjq.permissions.demo             I  Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2024-06-20 17:37:14.201  6685-6711  AdrenoGLES-0            com.hjq.permissions.demo             I  PFP: 0x016ee190, ME: 0x00000000
2024-06-20 17:37:14.210  6685-6711  libEGL                  com.hjq.permissions.demo             E  Invalid file path for libcolorx-loader.so
2024-06-20 17:37:14.216  6685-6711  chatty                  com.hjq.permissions.demo             I  uid=10291(com.hjq.permissions.demo) RenderThread identical 65 lines
2024-06-20 17:37:14.216  6685-6711  libEGL                  com.hjq.permissions.demo             E  Invalid file path for libcolorx-loader.so
2024-06-20 17:37:14.219  6685-6710  LeakCanary              com.hjq.permissions.demo             D  LeakCanary is running and ready to detect memory leaks.
2024-06-20 17:37:14.331  6685-6685  OplusFeatureCache       com.hjq.permissions.demo             I  Milliseconds spent on init(): 21
2024-06-20 17:37:14.332  6685-6685  ScreenmodeClient        com.hjq.permissions.demo             E   display mode not support 
2024-06-20 17:37:15.715  6685-6709  LeakCanary              com.hjq.permissions.demo             D  Setting up flushing for Thread[LeakCanary-Heap-Dump,5,main]
```

### 提供截图或视频

https://github.com/getActivity/XXPermissions/assets/16447251/65c4c99c-cb49-4f2c-b9d2-9e0da111b14e

**Comment by getActivity** [comment]
https://github.com/getActivity/XXPermissions/issues/227

**Comment by getActivity** [comment]
小伙子，你确定别人没有提过这个问题？

**Comment by xujiaji** [comment]
大佬，打扰了
