### ISSUE TITLE
[Bug]：公司定制的扫码枪申请拍照权限闪退

### ISSUE THREAD

**Issue by zhaichuankai** [getActivity/XXPermissions#319]
### 框架版本【必填】

16.8

### 问题描述【必填】

扫码枪安卓版本7.1.1，其他权限都正常，涉及到拍照权限就闪退，我使用你仓库的demo也是一样。

### 复现步骤【必填】

本仓库demo选项一：申请单个危险权限

### 是否必现【必填】

否

### 项目 targetSdkVersion【必填】

29

### 出现问题的手机信息【必填】

定制原生机

### 出现问题的安卓版本【必填】

7.1.1

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

暂时只发现本公司配备的扫码枪有出现

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
2024-08-27 18:05:19.310  2000-2000  wpa_supplicant          pid-2000                             D  wlan0: Control interface command 'SIGNAL_POLL'
2024-08-27 18:05:19.312  2000-2000  wpa_supplicant          pid-2000                             D  CTRL-DEBUG: global_ctrl_sock-sendto: sock=8 sndbuf=229376 outq=0 send_len=48
2024-08-27 18:05:19.334  1637-1637  BoostFramework          com.hjq.permissions.demo             V  BoostFramework() : mPerf = com.qualcomm.qti.Performance@9f3efbb
2024-08-27 18:05:19.376  1637-1774  LeakCanary              com.hjq.permissions.demo             D  Setting up flushing for Thread[LeakCanary-Heap-Dump,5,main]
2024-08-27 18:05:19.389   653-1740  AudioPolic...agerCustom pid-653                              I  FLAG None hence request for a primary output
2024-08-27 18:05:19.389   653-1125  AudioPolic...agerCustom pid-653                              I  FLAG None hence request for a primary output
2024-08-27 18:05:19.390   653-1056  audio_hw_primary        pid-653                              D  out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
2024-08-27 18:05:19.392   653-1056  audio_hw_primary        pid-653                              D  select_devices for use case (low-latency-playback)
2024-08-27 18:05:19.393   653-1056  audio_hw_extn           pid-653                              D  audio_extn_set_anc_parameters: anc_enabled:0
2024-08-27 18:05:19.393   653-1056  audio_hw_spkr_prot      pid-653                              D  audio_extn_fbsp_set_parameters: Speaker protection disabled
2024-08-27 18:05:19.425  1207-2472  ActivityManager         pid-1207                             I  START u0 {act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.android.packageinstaller cmp=com.android.packageinstaller/.permission.ui.GrantPermissionsActivity (has extras)} from uid 10109 on display 0
2024-08-27 18:05:19.431  1207-2472  ActivityTrigger         pid-1207                             D  ActivityTrigger activityPauseTrigger 
2024-08-27 18:05:19.489  3345-3345  BoostFramework          pid-3345                             V  BoostFramework() : mPerf = com.qualcomm.qti.Performance@b2c0283
2024-08-27 18:05:19.489  3345-3345  BoostFramework          pid-3345                             V  BoostFramework() : mPerf = com.qualcomm.qti.Performance@ed32c00
2024-08-27 18:05:19.559  3345-3365  Adreno-EGL              pid-3345                             I  <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (I762e720a6a)
                                                                                                    OpenGL ES Shader Compiler Version: XE031.09.00.04
                                                                                                    Build Date: 01/31/17 Tue
                                                                                                    Local Branch: 
                                                                                                    Remote Branch: 
                                                                                                    Local Patches: 
                                                                                                    Reconstruct Branch: 
2024-08-27 18:05:19.559  3345-3365  OpenGLRenderer          pid-3345                             I  Initialized EGL, version 1.4
2024-08-27 18:05:19.559  3345-3365  OpenGLRenderer          pid-3345                             D  Swap behavior 1
2024-08-27 18:05:19.608  1207-1357  ActivityManager         pid-1207                             I  Displayed com.android.packageinstaller/.permission.ui.GrantPermissionsActivity: +168ms
2024-08-27 18:05:19.732  1637-1637  ResourceType            com.hjq.permissions.demo             W  No package identifier when getting value for resource number 0x00000000
2024-08-27 18:05:20.046   485-590   libnav                  pid-485                              E  CablComputeBacklightLevel(): UpdateType = DifferentSceneUpdate
2024-08-27 18:05:20.605   653-1740  AudioPolic...agerCustom pid-653                              I  FLAG None hence request for a primary output
2024-08-27 18:05:20.605  1207-1375  ActivityManager         pid-1207                             I  Killing 1637:com.hjq.permissions.demo/u0a109 (adj 100): permission grant or revoke changed gids
2024-08-27 18:05:20.606  1207-1207  GnssLocationProvider    pid-1207                             I  WakeLock acquired by sendMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@31e8786)
2024-08-27 18:05:20.606  1207-1375  ActivityManager         pid-1207                             D  cleanUpApplicationRecord -- 1637
2024-08-27 18:05:20.607   653-1125  AudioPolic...agerCustom pid-653                              I  FLAG None hence request for a primary output
2024-08-27 18:05:20.607  1207-1375  ActivityManager         pid-1207                             W  Force removing ActivityRecord{b183cf8 u0 com.hjq.permissions.demo/.MainActivity t462}: app died, no saved state
2024-08-27 18:05:20.607  1207-1327  GnssLocationProvider    pid-1207                             I  WakeLock released by handleMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@31e8786)
2024-08-27 18:05:20.608   653-1056  audio_hw_primary        pid-653                              D  out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
2024-08-27 18:05:20.608   653-1056  audio_hw_primary        pid-653                              D  select_devices for use case (low-latency-playback)
2024-08-27 18:05:20.609   653-1056  audio_hw_extn           pid-653                              D  audio_extn_set_anc_parameters: anc_enabled:0
---------------------------- PROCESS ENDED (1637) for package com.hjq.permissions.demo ----------------------------
2024-08-27 18:05:20.609   653-1056  audio_hw_spkr_prot      pid-653                              D  audio_extn_fbsp_set_parameters: Speaker protection disabled
2024-08-27 18:05:20.629  1207-2010  GraphicsStats           pid-1207                             D  Buffer count: 8
2024-08-27 18:05:20.632  1207-1714  InputDispatcher         pid-1207                             W  channel 'f8918f1 com.hjq.permissions.demo/com.hjq.permissions.demo.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2024-08-27 18:05:20.632  1207-1714  InputDispatcher         pid-1207                             E  channel 'f8918f1 com.hjq.permissions.demo/com.hjq.permissions.demo.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2024-08-27 18:05:20.632  1207-1714  InputDispatcher         pid-1207                             W  channel '5aa806b PopupWindow:1e1b2a2 (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2024-08-27 18:05:20.632  1207-1714  InputDispatcher         pid-1207                             E  channel '5aa806b PopupWindow:1e1b2a2 (server)' ~ Channel is unrecoverably broken and will be disposed!
2024-08-27 18:05:20.637  1207-2473  WindowManager           pid-1207                             I  WIN DEATH: Window{5aa806b u0 PopupWindow:1e1b2a2}
2024-08-27 18:05:20.637  1207-2473  InputDispatcher         pid-1207                             W  Attempted to unregister already unregistered input channel '5aa806b PopupWindow:1e1b2a2 (server)'
2024-08-27 18:05:20.649  1207-2473  InputDispatcher         pid-1207                             W  Attempted to unregister already unregistered input channel 'f8918f1 com.hjq.permissions.demo/com.hjq.permissions.demo.MainActivity (server)'
2024-08-27 18:05:20.651  1207-24724 WindowManager           pid-1207                             W  Failed looking up window
                                                                                                    java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@b9cb898 does not exist
                                                                                                    	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9446)
                                                                                                    	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9437)
                                                                                                    	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1800)
                                                                                                    	at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
2024-08-27 18:05:20.651  1207-24724 WindowManager           pid-1207                             I  WIN DEATH: null
2024-08-27 18:05:20.665  1207-2472  ActivityTrigger         pid-1207                             D  ActivityTrigger activityPauseTrigger 
2024-08-27 18:05:20.755   485-590   libnav                  pid-485                              E  CablComputeBacklightLevel(): UpdateType = DifferentSceneUpdate
2024-08-27 18:05:20.863   485-590   libnav                  pid-485                              E  CablComputeBacklightLevel(): UpdateType = DifferentSceneUpdate
2024-08-27 18:05:20.871  3345-3365  OpenGLRenderer          pid-3345                             D  endAllActiveAnimators on 0x7f931ef400 (RippleDrawable) with handle 0x7facfffd20
2024-08-27 18:05:21.080   476-476   SurfaceFlinger          pid-476                              W  couldn't log to binary event log: overflow.
2024-08-27 18:05:21.202   485-590   libnav                  pid-485                              E  CablComputeBacklightLevel(): UpdateType = DifferentSceneUpdate
2024-08-27 18:05:22.318  2000-2000  wpa_supplicant          pid-2000                             D  wlan0: Control interface command 'SIGNAL_POLL'
2024-08-27 18:05:22.333  2000-2000  wpa_supplicant          pid-2000                             D  CTRL-DEBUG: global_ctrl_sock-sendto: sock=8 sndbuf=229376 outq=0 send_len=48
2024-08-27 18:05:23.755   653-1056  audio_hw_primary        pid-653                              D  out_standby: enter: stream (0xf45f4800) usecase(1: low-latency-playback)
2024-08-27 18:05:23.883   653-1056  audio_hw_primary        pid-653                              D  disable_audio_route: reset and update mixer path: low-latency-playback
2024-08-27 18:05:23.885   653-1056  soundtrigger            pid-653                              D  audio_extn_sound_trigger_update_stream_status: uc_id 1 of type 0 for Event 2, with Raise=0
2024-08-27 18:05:23.885   653-1056  hardware_info           pid-653                              D  hw_info_append_hw_type : device_name = speaker
2024-08-27 18:05:23.885   653-1056  audio_hw_primary        pid-653                              D  disable_snd_device: snd_device(2: speaker)
2024-08-27 18:05:23.885   653-1056  msm8916_platform        pid-653                              D  platform_can_split_snd_device: snd_device(2) num devices(0) new_snd_devices(0)
2024-08-27 18:05:23.888   653-1056  aud_dev_arbi            pid-653                              D  releaseOneDevice: not sending command, device argument (2) does not match any registered device
2024-08-27 18:05:23.888   653-1056  aud_dev_arbi            pid-653                              D  releaseOneDevice: device 2 owner is 0
2024-08-27 18:05:23.888   653-1056  soundtrigger            pid-653                              I  audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 0, with Raise=0
2024-08-27 18:05:23.888   653-1056  audio_hw_primary        pid-653                              D  out_standby: exit
2024-08-27 18:05:25.338  2000-2000  wpa_supplicant          pid-2000                             D  wlan0: Control interface command 'SIGNAL_POLL'
2024-08-27 18:05:25.341  2000-2000  wpa_supplicant          pid-2000                             D  CTRL-DEBUG: global_ctrl_sock-sendto: sock=8 sndbuf=229376 outq=0 send_len=48
```

**Comment by zhaichuankai** [comment]
感觉像是运行内存不足自动给进程回收掉了，但是为什么其他权限不会呢？

**Comment by getActivity** [comment]
@zhaichuankai 你既然知道是某个厂商系统的问题，为什么反馈给框架处理？
