### ISSUE TITLE
[Bug]：部分机型ActivityNotFoundException

### ISSUE THREAD

**Issue by Godsbox** [getActivity/XXPermissions#327]
### 框架版本【必填】

18.5

### 问题描述【必填】

android 13、14 部分机型， No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.android.permissioncontroller
Redmi表现是：No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.lbe.security.miui

### 复现步骤【必填】

申请Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE,
      Manifest.permission.CAMERA权限

### 是否必现【必填】

否

### 项目 targetSdkVersion【必填】

30

### 出现问题的手机信息【必填】

HONOR/ANY-AN00/android13; Redmi/23054RA19C/android13；HONOR/SDY-AN00/android14

### 出现问题的安卓版本【必填】

13,14

### 问题信息的来源渠道【必填】

umeng

### 是部分机型还是所有机型都会出现【必答】

部分： HONOR/ANY-AN00/android13; Redmi/23054RA19C/android13；HONOR/SDY-AN00/android14

### 框架最新的版本是否存在这个问题【必答】

不确定

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.lbe.security.miui (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2220)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:2006)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.vlite.sdk.client.hook.service.app.InstrumentationLiteApp.execStartActivity(InstrumentationLiteApp.java:503)
	at android.app.Activity.startActivityForResult(Activity.java:6488)
	at android.app.Activity$HostCallbacks.onRequestPermissionsFromFragment(Activity.java:9339)
	at android.app.Fragment.requestPermissions(Fragment.java:1233)
	at com.hjq.permissions.PermissionFragment.requestDangerousPermission(PermissionFragment.java:287)
	at com.hjq.permissions.PermissionFragment.requestSpecialPermission(PermissionFragment.java:221)
	at com.hjq.permissions.PermissionFragment.onResume(PermissionFragment.java:176)
	at android.app.Fragment.performResume(Fragment.java:2551)
	at android.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1346)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1642)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:2220)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:2166)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:2067)
	at android.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:742)
```
```text
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.android.permissioncontroller (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2302)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:2065)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.vlite.sdk.client.hook.service.app.InstrumentationLiteApp.execStartActivity(InstrumentationLiteApp.java:503)
	at android.app.Activity.startActivityForResult(Activity.java:6801)
	at android.app.Activity$HostCallbacks.onRequestPermissionsFromFragment(Activity.java:9821)
	at android.app.Fragment.requestPermissions(Fragment.java:1245)
	at com.hjq.permissions.PermissionFragment.requestDangerousPermission(PermissionFragment.java:287)
	at com.hjq.permissions.PermissionFragment.requestSpecialPermission(PermissionFragment.java:221)
	at com.hjq.permissions.PermissionFragment.onResume(PermissionFragment.java:176)
```

**Comment by getActivity** [comment]
<img width="830" alt="image" src="https://github.com/user-attachments/assets/ec5c952d-ce14-49df-8916-01143780c5f5">

**Comment by getActivity** [comment]
问题的原因大概率在这里，你可以顺着这条线往下排查

**Comment by Godsbox** [comment]
我的app没有这个东西，这代表目标手机系统的hook，还是说我们app被恶意篡改了？

**Comment by getActivity** [comment]
小伙子，针对你说的这个问题，我重新进行了研究，并研究出来了改进方案，后续我会提交到新版本（25.0）中，具体改动如下：

<img width="1218" height="776" alt="Image" src="https://github.com/user-attachments/assets/787bcf8d-9089-4a4f-b033-5cc9588f720b" />
