### ISSUE TITLE
Android最低版本只能是23吗？

### ISSUE THREAD

**Issue by tanranran** [getActivity/XXPermissions#68]
首先感谢作者提供这么好用的库，这个是我用过的中，体验最好的裤，没有之一。

由于某些原因，我的targetSdkVersion必须是22以下（因为狗日的libserial_port.so: has text relocations）

使用版本
```java
implementation 'com.hjq:xxpermissions:10.6'
```
我的代码
```java
XXPermissions.with(this)
        .permission(Permission.CAMERA)
        .request(new OnPermissionCallback() {
          @Override
          public void onGranted(List<String> permissions, boolean all) {
            if (all) {
              toast("获取相机权限成功");
              startCamera();
            } else {
              toast("获取部分权限成功，但部分权限未正常授予");
            }
          }

          @Override
          public void onDenied(List<String> permissions, boolean never) {
            if (never) {
              toast("被永久拒绝授权，请手动授予相机权限");
              XXPermissions.startPermissionActivity(FaceIdentifyActivity.this, permissions);
            } else {
              toast("获取相机权限失败");
            }
          }
        });
```

报错信息
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hemy.demo4java/com.hemy.demo4java.FaceIdentifyActivity}: java.lang.RuntimeException: The targetSdkVersion SDK must be 23 or more
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)
     Caused by: java.lang.RuntimeException: The targetSdkVersion SDK must be 23 or more
        at com.hjq.permissions.PermissionChecker.checkTargetSdkVersion(PermissionChecker.java:211)
        at com.hjq.permissions.XXPermissions.request(XXPermissions.java:156)
```

看了下源码，原因是代码中限定死了只能最低是23
```java
 static void checkTargetSdkVersion(Context context, List<String> requestPermissions) {
        // targetSdk 最低版本要求
        int targetSdkMinVersion;
        if (requestPermissions.contains(Permission.MANAGE_EXTERNAL_STORAGE)) {
            // 必须设置 targetSdkVersion >= 30 才能正常检测权限，否则请使用 Permission.Group.STORAGE 来申请存储权限
            targetSdkMinVersion = Build.VERSION_CODES.R;
        } else if (requestPermissions.contains(Permission.ACCEPT_HANDOVER)) {
            targetSdkMinVersion = Build.VERSION_CODES.P;
        } else if (requestPermissions.contains(Permission.ACCESS_BACKGROUND_LOCATION) ||
                requestPermissions.contains(Permission.ACTIVITY_RECOGNITION) ||
                requestPermissions.contains(Permission.ACCESS_MEDIA_LOCATION)) {
            targetSdkMinVersion = Build.VERSION_CODES.Q;
        } else if (requestPermissions.contains(Permission.REQUEST_INSTALL_PACKAGES) ||
                requestPermissions.contains(Permission.ANSWER_PHONE_CALLS) ||
                requestPermissions.contains(Permission.READ_PHONE_NUMBERS)) {
            targetSdkMinVersion = Build.VERSION_CODES.O;
        } else {
            targetSdkMinVersion = Build.VERSION_CODES.M;
        }
        // 必须设置正确的 targetSdkVersion 才能正常检测权限
        if (context.getApplicationInfo().targetSdkVersion < targetSdkMinVersion) {
            throw new RuntimeException("The targetSdkVersion SDK must be " + targetSdkMinVersion + " or more");
        }
    }
```

跪求大佬支持下22版本

**Comment by getActivity** [comment]
框架检查 targetSdkVersion 版本的目的：如果申请的权限和项目中的 targetSdkVersion 对不上，框架会抛出异常，是因为 targetSdkVersion 代表着项目适配到哪个 Android 版本，系统会自动做向下兼容，假设申请的权限是 Android 11 才出现的，但是 targetSdkVersion 还停留在 29，那么在某些机型上的申请结果会出现异常的情况。

**Comment by tanranran** [comment]
@getActivity 但是我只是申请相机权限 Permission.CAMERA，最低只能23吗？

**Comment by getActivity** [comment]
* 如果你不想收到此异常提醒，建议你在应用初始化时加入
```java
XXPermissions.setDebugMode(false);
```
* 这样框架就不会帮你检查任何低级错误

**Comment by tanranran** [comment]
@getActivity 666，大佬牛逼，这种方法都有。

**Comment by getActivity** [comment]
@tanranran 可以申请，但是曾经有人反馈过，因为 targetSdkVersion 设置 23 以下，在某些机型上面可能会出现申请异常，这点你要清楚。

**Comment by tanranran** [comment]
@getActivity 好的，异常了再说，到时候提示用户此功能不对该设备提供

**Comment by getActivity** [comment]
好的，小伙子，还有其他问题不，没有的话记得手动关闭一下 issue。

**Comment by tanranran** [comment]
@getActivity 没有了，感谢大佬，祝大佬夜夜笙箫，次次8连发
