### ISSUE TITLE
添加权限报错

### ISSUE THREAD

**Issue by fuqiang229844586** [getActivity/XXPermissions#73]
读写存储权限报错/demo闪退：
.permission(Permission.READ_EXTERNAL_STORAGE)
.permission(Permission.WRITE_EXTERNAL_STORAGE)
传入系统的值是一样
Manifest.permission.WRITE_EXTERNAL_STORAGE,
Manifest.permission.READ_EXTERNAL_STORAGE
——————————————————————————————————————
就在大神你的demo里面
else if (viewId == R.id.btn_main_request_2) {
            XXPermissions.with(this)
                    .permission(Permission.READ_EXTERNAL_STORAGE)
                    .permission(Permission.WRITE_EXTERNAL_STORAGE)
                    .request(new OnPermissionCallback() {

                        @Override
                        public void onGranted(List<String> permissions, boolean all) {
                            if (all) {
                                toast("获取录音和日历权限成功");
                            }
                        }
                    });
        } 
——————————————————————————————————————
demo错误日志：
Process: com.hjq.permissions.demo, PID: 5977
    java.lang.IllegalArgumentException: Please adapt the scoped storage, or use the MANAGE_EXTERNAL_STORAGE permission
        at com.hjq.permissions.PermissionChecker.checkStoragePermission(PermissionChecker.java:150)
        at com.hjq.permissions.XXPermissions.request(XXPermissions.java:152)
        at com.hjq.permissions.demo.MainActivity.onClick(MainActivity.java:66)
        at android.view.View.performClick(View.java:7261)
        at android.view.View.performClickInternal(View.java:7223)
        at android.view.View.access$3800(View.java:824)
        at android.view.View$PerformClick.run(View.java:27721)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:238)
        at android.app.ActivityThread.main(ActivityThread.java:7798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by getActivity** [comment]
小伙子，这个报错是框架给你抛的，报错代码那里的注释有说明解决方案，你按照上面的指引来做就可以了。
