### ISSUE TITLE
请求权限点击同意或者拒绝会报错，并且没有执行回调

### ISSUE THREAD

**Issue by ximenchuipaopao** [getActivity/XXPermissions#79]
## 问题描述

* 框架版本：11

* 问题描述：请求权限点击同意或者拒绝会报错WindowManager: android.view.WindowLeaked: Activity com.android.packageinstaller.permission.ui.GrantPermissionsActivity has leaked window DecorView@15d1089[GrantPermissionsActivity] that was originally added here ，并且不会执行回调 ，运行你的demo没有出现这个问题，然后我把你demo的 manifest文件权限 、application里的配置都复制到我的项目中也是一样的情况，华为荣耀android 8 也是一样的问题，分析不出问题所在了，请指点下不知道我是不是少了什么配置，QQ群加了一直没通过

* 复现步骤：请求权限，权限弹出后点击同意或者拒绝都会出现

* 是否必现：是

* 手机信息：红米k40 android 11

## 请回答

* 是部分机型还是所有机型都会出现：是

* 框架最新的版本是否存在这个问题：是

* 是否已经查阅框架文档还未能解决的：是

* issue 是否有人曾提过类似的问题：否

* 是否可以通过 Demo 来复现该问题：否

## 其他

* 提供报错堆栈（如果有报错的话必填）
* WindowManager: android.view.WindowLeaked: Activity com.android.packageinstaller.permission.ui.GrantPermissionsActivity has leaked window DecorView@15d1089[GrantPermissionsActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:779)
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:763)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:399)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:111)
        at android.app.Dialog.show(Dialog.java:342)
        at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.showDialog(Unknown Source:29)
        at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.onCreate(Unknown Source:634)
        at android.app.Activity.performCreate(Activity.java:8143)
        at android.app.Activity.performCreate(Activity.java:8115)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1308)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3503)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3690)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8053)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

* 提供截图或视频（根据需要提供，不强制）

* 提供解决方案（如果已经解决了的话）

**Comment by getActivity** [comment]
小伙子，QQ 群我已经通过了，由于 QQ 群是禁言状态，你可以发私信给我，我收到之后会处理的。

**Comment by getActivity** [comment]
已在 QQ 上面协助处理该问题，故关闭此 issue。

**Comment by tuionf** [comment]
了解一下这个是怎么解决的
