### ISSUE TITLE
Android11 关于这权限的问题 Manifest.permission.ACCESS_MEDIA_LOCATION

### ISSUE THREAD

**Issue by hyl87** [getActivity/XXPermissions#80]
## 问题描述

* 框架版本：11.0

* 问题描述：XXX

* 复现步骤：XXX

* 是否必现：填是/否

* 手机信息：小米10

Manifest.permission.ACCESS_MEDIA_LOCATION 这个权限在动态申请权限时选择仅在使用中允许,然后在获取照片位置信息的时候 会报错java.lang.UnsupportedOperationException: Caller must hold ACCESS_MEDIA_LOCATION permission to access original

选择始终允许就不会报错

找了不半天也不知道怎么解决这个问题

所以前来求助,看看该如何解决这个问题

**Comment by getActivity** [comment]
小伙子，你是在前台状态下使用该权限还是在后台状态下使用该权限？

**Comment by hyl87** [comment]
> 小伙子，你是在前台状态下使用该权限还是在后台状态下使用该权限？还有使用原生 API 是否有这个问题呢？

前台,动态申请权限的,原生api没试过,只要是给 仅在使用中允许 的状态就会报错,始终允许就不会
我一会试下原生的api看看

**Comment by hyl87** [comment]
> > 小伙子，你是在前台状态下使用该权限还是在后台状态下使用该权限？还有使用原生 API 是否有这个问题呢？
> 
> 前台,动态申请权限的,原生api没试过,只要是给 仅在使用中允许 的状态就会报错,始终允许就不会
> 我一会试下原生的api看看

用原生也是一样的错误,看了官方文档,也没发现为什么

只要选择 <<仅在使用中允许>> 就会有问题

java.lang.UnsupportedOperationException: Caller must hold ACCESS_MEDIA_LOCATION permission to access original
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:174)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2010)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1825)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1502)

**Comment by getActivity** [comment]
@hyl87 小伙子，因为框架是基于原生 API 去封装的，你自己试了也会，所以这个应该是谷歌的 Bug，框架的代码是没有问题的，我这边建议你这自行捕获此异常，然后提醒给到用户，除此之外没有更好的方法。

**Comment by getActivity** [comment]
检查一下存储权限是否正常授予，然后你在清单文件中加入这个属性试试看：
android:requestLegacyExternalStorage="true"

**Comment by hyl87** [comment]
> 检查一下存储权限是否正常授予，然后你在清单文件中加入这个属性试试看行不行：
> `android:requestLegacyExternalStorage="true"`

加了的,问题是 捕获不到,直接crash的异常

**Comment by getActivity** [comment]
小伙子，这个可能要靠你自己排查一下了，建议你使用谷歌搜索一下报错信息，如果后面有解决方案了记得跟我这边说一下。

**Comment by hyl87** [comment]
找到原因了，在android10 以上，开启分区储存后
要用这两个组合  
android.Manifest.permission.ACCESS_MEDIA_LOCATION, 
android.Manifest.permission.MANAGE_EXTERNAL_STORAGE 去申请权限
我之前是下面这种
android.Manifest.permission.ACCESS_MEDIA_LOCATION
android.Manifest.permission.READ_EXTERNAL_STORAGE,
 android.Manifest.permission.WRITE_EXTERNAL_STORAGE.

目前我只是在小米10上测试通过，其他手机就不知道有没有问题

**Comment by getActivity** [comment]
小伙子，麻烦提供一下获取照片位置信息相关的代码，我这边要做一下测试

**Comment by hyl87** [comment]
```kotlin
class AndroidMediaManager(private val plaformContext: Context) : MediaManager {

    private fun convertRationalLatLonToFloat(rationalString: String, ref: String): Double {
        val parts = rationalString.split(",").toTypedArray()
        var pair: Array<String> = parts[0].split("/").toTypedArray()
        val degrees = pair[0].trim { it <= ' ' }.toDouble() / pair[1].trim { it <= ' ' }.toDouble()
        pair = parts[1].split("/").toTypedArray()
        val minutes = pair[0].trim { it <= ' ' }.toDouble() / pair[1].trim { it <= ' ' }.toDouble()
        pair = parts[2].split("/").toTypedArray()
        val seconds = pair[0].trim { it <= ' ' }.toDouble() / pair[1].trim { it <= ' ' }.toDouble()
        val result = degrees + minutes / 60.0 + seconds / 3600.0
        return if (ref == "S" || ref == "W") (-result) else result
    }

    private fun getExifInterface(uri: Uri, contentResolver: ContentResolver): ExifInterface? {
        return if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.Q) {
            val photoUri = MediaStore.setRequireOriginal(uri)
            contentResolver.openInputStream(photoUri)?.use { stream -> ExifInterface(stream) }
        } else {
            val file = UriUtils.uri2File(uri)
            ExifInterface(file)
        }

    }

    override suspend fun getImageList(pageIndex: Long, pageSize: Int): MutableList<MediaBean> {
        val videoList = mutableListOf<MediaBean>()

        val projection = arrayOf(
            MediaStore.Images.Media._ID,
            MediaStore.Images.Media.DISPLAY_NAME,
            MediaStore.Images.Media.SIZE,
            MediaStore.Images.Media.WIDTH,
            MediaStore.Images.Media.HEIGHT,
            MediaStore.Images.Media.DATE_ADDED
        )

        val sortOrder = "${MediaStore.Images.Media.DATE_ADDED}  DESC"
        val query = plaformContext.contentResolver.query(
            MediaStore.Images.Media.EXTERNAL_CONTENT_URI,
            projection,
            null,
            null,
            sortOrder
        )
        buildData(query, videoList)

        return videoList
    }

    private fun buildData(query: Cursor?, videoList: MutableList<MediaBean>) {
        query?.use { cursor ->
            // Cache column indices.
            val idColumn = cursor.getColumnIndexOrThrow(MediaStore.Images.Media._ID)
            val nameColumn = cursor.getColumnIndexOrThrow(MediaStore.Images.Media.DISPLAY_NAME)
            val wColumn = cursor.getColumnIndexOrThrow(MediaStore.Images.Media.WIDTH)
            val hColumn = cursor.getColumnIndexOrThrow(MediaStore.Images.Media.HEIGHT)
            val addTimeColumn = cursor.getColumnIndexOrThrow(MediaStore.Images.Media.DATE_ADDED)

            while (cursor.moveToNext()) {
                val id = cursor.getString(idColumn)
                val name = cursor.getString(nameColumn)
                //val size = cursor.getInt(sizeColumn)
                val w = cursor.getInt(wColumn)
                val h = cursor.getInt(hColumn)
                val addTime = cursor.getLong(addTimeColumn)

                val contentUri: Uri = Uri.withAppendedPath(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, id)
                val exifInterface = getExifInterface(contentUri, plaformContext.contentResolver)
                exifInterface?.let {
                    val latLong = exifInterface.latLong ?: doubleArrayOf(0.0, 0.0)
                    val time = it.getAttribute(ExifInterface.TAG_DATETIME)
                    val date = if (!time.isNullOrEmpty()) {
                        TimeUtils.string2Millis(time, TimeUtils.getSafeDateFormat("yyyy:MM:dd HH:mm:ss"))
                    } else {
                        File(contentUri.path).lastModified()
                    }

                    if (date > 0) {
                        val bean = if (latLong[1] > 0 && latLong[0] > 0) {
                            MediaBean(name, contentUri.toString(), w, h, date, Location(latLong[1], latLong[0]), addTime)
                        } else {
                            MediaBean(name, contentUri.toString(), w, h, date, Location(0.0, 0.0), addTime)
                        }

                        videoList += bean
                    }

                }


            }
        }
    }

    override suspend fun getRecentMediaList(lastAddTime: Long): MutableList<MediaBean> {
        val videoList = mutableListOf<MediaBean>()

        val projection = arrayOf(
            MediaStore.Images.Media._ID,
            MediaStore.Images.Media.DISPLAY_NAME,
            MediaStore.Images.Media.SIZE,
            MediaStore.Images.Media.WIDTH,
            MediaStore.Images.Media.HEIGHT,
            MediaStore.Images.Media.DATE_ADDED
        )

        /*val selection = "${MediaStore.Images.Media.ALBUM} >= ?"
        val selectionArgs = arrayOf(
            TimeUnit.MILLISECONDS.convert(5, TimeUnit.MINUTES).toString()
        )*/

        val sortOrder = "${MediaStore.Images.Media.DATE_ADDED} DESC"

        val query = plaformContext.contentResolver.query(
            MediaStore.Images.Media.EXTERNAL_CONTENT_URI,
            projection,
            "${MediaStore.Images.Media.DATE_ADDED} > ?",
            arrayOf("$lastAddTime"),
            sortOrder
        )

        buildData(query, videoList)

        return videoList
    }

}
```
@getActivity

**Comment by getActivity** [comment]
多谢小伙子的反馈，已经记录到框架代码注释中，会在下个版本发布更新
